// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/user-details/:userId": {
    params: {
      "userId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/user-details/:userId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/user-details.tsx": {
    id: "routes/user-details";
    page: "/user-details/:userId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/user-details": typeof import("./app/routes/user-details.tsx");
};